### ISSUE TITLE
node registration issues and init.lua issue

### ISSUE THREAD

**Issue by DragonWrangler1** [Darin755/minetest-uptime-stats#5]
each node name  has "stats:” before the actual node itself but it either needs to be :stats: or digiline_stats:
due to the mod name if you want the registration name to be different than the mod name then this prefix is required “:”

and in init.lua 

it seems that  how you defined “path” doesn't want to work properly so it crashes

here is how you defined it "local path = minetest.get_modpath("stats")"

and here is a suitable working alternative

local modname = minetest.get_current_modname()
local path = minetest.get_modpath(modname)

here is a pull request I made

https://github.com/Darin755/minetest-uptime-stats/pull/6

**Comment by Darin755** [comment]
This issue should be fixed with your PR. I'm going to go ahead and close this but feel free to reopen if you feel that it isn't completed.
